workflows:
  android-build:
    name: Android Build
    environment:
      flutter: stable
      android-sdk-components: 
        - "build-tools;34.0.0" 
        - "platforms;android-34" 
    scripts:
      - flutter pub get
      - flutter build appbundle --release 
    artifacts:
      - build/app/outputs/bundle/release/*.aab
