name: LCC
description: "Nitrogen Fertilizer Recommendation System for Paddy Field using AI."

publish_to: "none"

version: 1.0.0+2

environment:
  sdk: ">=3.4.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  hooks_riverpod: ^3.0.0-dev.3
  flutter_hooks: null
  riverpod_annotation: ^3.0.0-dev.3
  image: ^4.2.0
  path_provider: ^2.1.3
  tflite_flutter: ^0.11.0
  percent_indicator: ^4.2.3
  syncfusion_flutter_gauges: ^22.2.12
  path: ^1.9.0
  freezed_annotation: ^2.4.3
  camera: ^0.11.0+1
  logger: ^2.3.0
  pretty_print_json: ^1.0.1
  dartz: ^0.10.1
  loader_overlay: ^4.0.1
  flutter_spinkit: ^5.2.1
  simple_progress_indicators: ^0.2.0
  flutter_launcher_icons: ^0.14.3
  image_picker: ^1.1.2
  permission_handler: ^11.1.0
  device_info_plus: ^11.2.2
  carousel_slider: ^5.0.0
  shared_preferences: ^2.2.2
  flutter_local_notifications: ^18.0.1
  timezone: ^0.10.0
  hive: ^2.2.3
  hive_flutter:


dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner: null
  custom_lint: null
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  flutter_lints: ^4.0.0
  freezed: ^2.5.2
  dropdown_button2: ^2.3.9
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true

  assets:
    - assets/tflite/
    - assets/icons/
    - assets/images/

  fonts:
    - family: Manrope
      fonts:
        - asset: fonts/Manrope-Regular.ttf
        - asset: fonts/Manrope-SemiBold.ttf
        - asset: fonts/Manrope-Bold.ttf
