name: rice_fertile_ai
description: "Nitrogen Fertilizer Recommendation System for Paddy Field using AI."

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.3 <4.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  flutter_svg: ^2.0.7
  hooks_riverpod: ^3.0.0-dev.3
  flutter_hooks:
  riverpod_annotation: ^3.0.0-dev.3
  image: ^3.3.0
  path_provider: ^2.1.3
  tflite_flutter: ^0.10.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  build_runner:
  custom_lint:
  riverpod_generator: ^3.0.0-dev.11
  riverpod_lint: ^3.0.0-dev.4
  flutter_lints: ^4.0.0
  image_picker: ^0.8.5+3
  percent_indicator: ^4.2.3
  syncfusion_flutter_gauges: ^22.2.12

flutter:
  uses-material-design: true

  assets:
    - assets/tflite/
    - assets/images/
    - assets/fonts/
    - assets/icons/
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
